// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJJKrnIH3mqiaO8lsnWreZAL5c19RKe0',
    appId: '1:735079555774:web:eeefc5a7719e51aa0a34ef',
    messagingSenderId: '735079555774',
    projectId: 'echno-attendance-project',
    authDomain: 'echno-attendance-project.firebaseapp.com',
    storageBucket: 'echno-attendance-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6u0IujY_YgQIXiiguV1wTTLyePYgeYc',
    appId: '1:735079555774:android:9fa1f1d3c6ca6dfe0a34ef',
    messagingSenderId: '735079555774',
    projectId: 'echno-attendance-project',
    storageBucket: 'echno-attendance-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JWJPVv4qu9ToDCejVJhuyWoCxw7yw50',
    appId: '1:735079555774:ios:a813844b1e0bfdf50a34ef',
    messagingSenderId: '735079555774',
    projectId: 'echno-attendance-project',
    storageBucket: 'echno-attendance-project.appspot.com',
    iosClientId: '735079555774-1t2kleba7tb7ah3evl8q3l9vkjcar0kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.echnoAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JWJPVv4qu9ToDCejVJhuyWoCxw7yw50',
    appId: '1:735079555774:ios:fd5460a4f2ce7b950a34ef',
    messagingSenderId: '735079555774',
    projectId: 'echno-attendance-project',
    storageBucket: 'echno-attendance-project.appspot.com',
    iosClientId: '735079555774-0vlt4atk8pjs806sbo686f1qgo8r412n.apps.googleusercontent.com',
    iosBundleId: 'com.example.echnoAttendance.RunnerTests',
  );
}
